#!/bin/bash
#
# author: gh/mateossh
# dependencies: wget

DISCORD_TAR="https://discordapp.com/api/download?platform=linux&format=tar.gz"

if [ -f /tmp/discord.tar.gz ]; then
  rm /tmp/discord.tar.gz
fi

echo "Downloading Discord..."
wget --show-progress --progress=bar --quiet -O /tmp/discord.tar.gz $DISCORD_TAR
echo "Extracting Discord..."
mkdir -p /tmp/discord
tar -xf /tmp/discord.tar.gz  -C /tmp/discord

echo "Copying Discord..."
sudo cp -rf /tmp/discord/Discord /opt/discord

if [ ! -f /usr/local/bin/discord ]; then
  echo "Linking Discord to path"
  sudo ln -s /opt/discord/Discord /usr/local/bin/discord
fi
