#!/bin/bash

duration=0.5

barw=100
barh=35
barx=$(xdpyinfo | grep dimensions | tr -s ' ' ';' | cut -f 3 -d ';' | cut -f 1 -d 'x')
bary=$(xdpyinfo | grep dimensions | tr -s ' ' ';' | cut -f 3 -d ';' | cut -f 2 -d 'x')
let barx=${barx}/2-${barw}/2
let bary=${bary}*4/5

bar_bg='#3d3d3d00'
bar_fg='#ffffffff'

bar_font_1='xft:Iosevka:style=Regular:pixelsize=13'
bar_font_2='FontAwesome'
# bar_font_1='-misc-iosevka-medium-r-normal-*-12-100-90-90-*-*-*-*'
# bar_font_2='-*-fontawesome-*-*-*-*-*-*-*-*-*-*-*-*'

baropt="-d -g ${barw}x${barh}+${barx}+${bary} -f ${bar_font_1} -f ${bar_font_2} -F ${bar_fg} -B ${bar_bg}"


(echo -e "${1}"; sleep "${duration}") | lemonbar ${baropt}
