#!/bin/sh
#
# author: github/randomn4me
# dependencies: ffmpeg

DIR="$HOME/Videos/screencasts"
DATE=$(date '+%F_%H-%M')

MW=$(xdotool getdisplaygeometry | awk -F ' ' '{print $1}')
MH=$(xdotool getdisplaygeometry | awk -F ' ' '{print $2}')

ffmpeg -f x11grab \
       -r 30 \
			 -s ${MW}x${MH} \
			 -i :0.0 \
       -loglevel quiet \
			 -vcodec libx264 \
			 -preset ultrafast \
			 -threads 0 \
			 -y "$DIR/$DATE.mkv"
